In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import math

%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [9]:
data = {'Student_ID': [1,2,3,4,5],
       'Math_score': [90,np.nan,87,99,80],
       'Science_score': [88,np.nan,76,85,92]}
df = pd.DataFrame(data)
df

Student_ID  Math_score  Science_score
0           1        90.0           88.0
1           2         NaN            NaN
2           3        87.0           76.0
3           4        99.0           85.0
4           5        80.0           92.0

### Preprocessing

##### Imputation

In [11]:
vals = {'Math_score':df.Math_score.mean(), 'Science_score':df.Science_score.mean()}
df.fillna(vals)

Student_ID  Math_score  Science_score
0           1        90.0          88.00
1           2        89.0          85.25
2           3        87.0          76.00
3           4        99.0          85.00
4           5        80.0          92.00

### Outliers and Duplicates

##### Outliers with Z score

In [18]:
data = np.array([2.0,2.2,2.4,2.8,3.0,3.2,3.4,4.0,100.0])
data

array([  2. ,   2.2,   2.4,   2.8,   3. ,   3.2,   3.4,   4. , 100. ])

In [24]:
z_scores = np.abs(stats.zscore(data))
threshold = 2
ouliers  = z_scores > threshold
data[ouliers]

array([100.])

#### Outliers with IQR

In [43]:
data = np.array([2.0,2.2,2.4,2.8,3.0,3.2,3.4,4.0,105.0])
data

array([  2. ,   2.2,   2.4,   2.8,   3. ,   3.2,   3.4,   4. , 105. ])

In [45]:
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 72)

iqr = q3-q1
iqr

0.952

In [47]:
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

In [49]:
outliers = np.where((data>upper_bound) | (data<lower_bound))
data[outliers]

array([105.])