# Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

#### What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [2]:
import numpy as np

In [4]:
list=[1,2,3,4,5]

In [6]:
arr=np.array(list)

In [8]:
arr

array([1, 2, 3, 4, 5])

In [10]:
type(arr)

numpy.ndarray

In [20]:
lst1=[1,2,3]
lst2=[4,5,6]
lst3=[7,8,9]

arr=np.array([lst1,lst2,lst3])

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr.shape

(3, 3)

In [34]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [46]:
arr[1:,:2] #array slicing

array([[2, 3],
       [9, 7]])

In [48]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
arr1=np.arange(0,10).reshape(2,5)

In [52]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [56]:
## random distribution
np.random.rand(3,3)

array([[0.71985619, 0.50375587, 0.28547209],
       [0.10460379, 0.34381314, 0.17130524],
       [0.62072242, 0.30665996, 0.98849356]])